on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  package_pyz:
    name: Package zipapp
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: make pyz
      - name: Archive pyz
        uses: actions/upload-artifact@v4
        with:
          name: "pyz"
          path: "kqf.pyz"
          if-no-files-found: error
          retention-days: 30