on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  determine_version:
    name: Determine version constants
    runs-on: ubuntu-22.04
    outputs:
      shortsha: ${{ steps.consts.outputs.GIT_SHORTSHA }}
      describe: ${{ steps.consts.outputs.GIT_DESCRIBE }}
      tagname: ${{ steps.consts.outputs.SNAP_TAGNAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Determine Constants
        id: consts
        run: |
          set -x
          GIT_SHORTSHA="$(git show-ref --abbrev "${GITHUB_REF}" | cut -f 1 -d' ')"
          GIT_DESCRIBE="$(git describe --always --tags --exclude '*-alpha*' --exclude '*-snapshot*')"
          SNAP_TAGNAME="${GIT_SHORTSHA}-snapshot"
          cat <<END_ENV > "$GITHUB_OUTPUT"
          GIT_SHORTSHA="${GIT_SHORTSHA}"
          GIT_DESCRIBE="${GIT_DESCRIBE}"
          SNAP_TAGNAME="${SNAP_TAGNAME}"
          END_ENV

  package_pyz:
    name: Package zipapp
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: make pyz
      - name: Archive pyz
        uses: actions/upload-artifact@v4
        with:
          name: "pyz"
          path: "kqf.pyz"
          if-no-files-found: error
          retention-days: 30
  release:
    name: Create/Update prerelease
    runs-on: ubuntu-22.04
    needs:
     - determine_version
    env:
      GIT_SHORTSHA: ${{ needs.determine_version.outputs.shortsha }}
      GIT_DESCRIBE: ${{ needs.determine_version.outputs.describe }}
      SNAP_TAGNAME: ${{ needs.determine_version.outputs.tagname }}
    steps:
      - name: Create release object if not exists
        run: |
          gh release view "$SNAP_TAGNAME" &>/dev/null
          release_exists=$?
          if ! $release_exists; then
            git tag "$SNAP_TAGNAME"
            git push origin "$SNAP_TAGNAME"
            gh release -p "$SNAP_TAGNAME" -n "Auto snapshot" -t "Development Snapshot $GIT_DESCRIBE"
          fi
      - name: Get pyz artifact
        uses: actions/download-artifact@v4
        with:
          name: pyz
      - name: Upload pyz
        run:
          gh release "${SNAP_TAGNAME}" upload --clobber kqf.pyz


